- name: Adding 10 users in all servers
  user: 
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    loop:
      - user1
      - user2
      - user3
      - user4
      - user5 
      - user6
      - user7 
      - user8
      - user9
      - user10 

      
